spring.application.name=LibraryAppCacheSpring
spring.datasource.url=jdbc:sqlite:library.db
spring.datasource.driver-class-name=org.sqlite.JDBC
server.port=8081
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=student
spring.rabbitmq.password=student
rabbitmq.exchange=direct
rabbitmq.file.queue=file.queue
rabbitmq.commands.queue=commands.queue
rabbitmq.state.queue=state.queue
rabbitmq.file.routing-key=file
rabbitmq.commands.routing-key=commands
rabbitmq.state.routing-key=state