spring.application.name=demo
spring.datasource.url=jdbc:sqlite:beer.db
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=student
spring.rabbitmq.password=student
beerapp.rabbitmq.exchange=beerapp.direct
beerapp.rabbitmq.request.queue=beerapp.request.queue
beerapp.rabbitmq.request.routing-key=beerapp.request
beerapp.rabbitmq.response.queue=beerapp.response.queue
beerapp.rabbitmq.response.routing-key=beerapp.response
