message_manager:
	./docker* localhost:5000/message_manager_microservice:v1

teacher:
	./docker* localhost:5000/teacher_microservice:v1

student:
	./docker* "localhost:5000/student_microservice:v${ID}"
