server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore/Cheltuieli.p12
server.ssl.key-store-password=sd_lab_04
server.ssl.key-alias=Cheltuieli
server.ssl.enabled=true

spring.datasource.url=jdbc:sqlite:cheltuieli.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=always